### PR TITLE
Add Academic Work to front-page

### PR DESCRIPTION
**Pull request by c00k133**
Add Academic Work as a Nationsföretag.

### CODE REVIEW

**Comment by walliski** [comment]
Do we have permission to redistribute their logo? If not, it should probably not be in the repo. Else I guess it looks good.

**Review by walliski — APPROVED** [review]

**Comment by CastorK** [comment]
> Do we have permission to redistribute their logo? If not, it should probably not be in the repo. Else I guess it looks good.

I dont think we have actually agreed with any of the companies about redistributing their logos :sweat_smile:

**Review by CastorK — APPROVED** [review]

**Comment by VonLatvala** [comment]
As long as they didn’t explicitly forbid us I’d say it’s fine.

Axel Latvala
Aalto University / SCI / CS
Oy Aimo Latvala Ab /
CTO

**Comment by walliski** [comment]
My vote would be: As long as they permit us to redistribute their stuff, it is okay, else it is not. Not the easy way for us, but the right way of doing it.

**Comment by c00k133** [comment]
@walliski @CastorK 
This logo was given to me by the "Näringslivsansvariga", so it should be alright. I'll double-check with her, if OK I'll merge.

**Comment by c00k133** [comment]
We got green light!

I'll deploy later today

**Pull request merged**
